# Generated by Django 4.1 on 2023-04-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_Name', models.CharField(default='', max_length=255, null=True)),
                ('file_upload_date', models.DateField(default='', null=True)),
                ('file_data', models.FileField(default='', null=True, upload_to='files')),
            ],
        ),
    ]
