# Generated by Django 4.1 on 2023-04-12 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, null=True)),
                ('email', models.CharField(default='', max_length=255, null=True)),
                ('pasword', models.CharField(default='', max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='uploadfiles',
            name='file_upload_date',
        ),
        migrations.AddField(
            model_name='uploadfiles',
            name='reg_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Analysis_App.registeruser'),
        ),
    ]
