# Generated by Django 4.1 on 2023-04-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis_App', '0003_uploadfiles_file_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfiles',
            name='file_data',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
